# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

   jobs:
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: setup Zdk
    - uses: actions/setup-java@v3
      with:
       distribution: 'zulu' # See 'Supported distributions' for available options
       java-version: '21'
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
    - name: build
      run: ./gradlew build
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build/libs/
